import type { CaseFile, ChatTurn } from "./types"

export const fraudScript: ChatTurn[] = [
  {
    kind: "alert",
    title: "FRAUD ALERT",
    lines: ["$1,284.67 at LUXEMARKET.COM", "Debit card ····1842 · \"This wasn't me\""],
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Hi Maya. I'm Ava, NorthStar's virtual banking assistant. I already have the transaction you flagged, so you won't need to enter it again. You said the $1,284.67 LUXEMARKET.COM transaction wasn't yours. Is that correct?",
  },
  { kind: "reply", text: "Yes. I've never even heard of that merchant." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "I'm sorry — let's secure things first. You're already signed into the app. Before I make security changes, please confirm with Face ID. I will never ask you for your PIN, password, or a one-time code in this chat.",
  },
  { kind: "system", text: "Identity confirmed." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Thank you. Do you still have the physical debit card ending 1842 with you?",
  },
  { kind: "reply", text: "Yes, it's in my wallet." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Understood. Does anyone else have permission to use this card or this checking account?",
  },
  { kind: "reply", text: "No. Just me." },
  { kind: "system", text: "Checking recent activity…" },
  {
    kind: "transactions",
    items: [
      { label: "QuickCash ATM", amount: "$600.00", time: "Today, 9:51 AM" },
      { label: "MetroRide", amount: "$19.42", time: "Today, 8:14 AM" },
    ],
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "I found two other transactions I'd like you to review. Which of those do you recognize?",
  },
  { kind: "reply", text: "MetroRide is mine. The ATM withdrawal isn't — I haven't used an ATM today." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Thank you. I've marked MetroRide as recognized, and marked the $600 ATM withdrawal and the LUXEMARKET.COM purchase as disputed.",
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Because there are two unauthorized transactions across different channels, I recommend freezing card 1842 immediately while we investigate. Your checking account will remain open. Shall I freeze the card now?",
  },
  { kind: "reply", text: "Yes, freeze it." },
  { kind: "system", text: "Card status: BLOCKED — suspected fraud." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Done. Card ending 1842 is now frozen. One more security question: in the last few days, did anyone contact you claiming to be NorthStar and ask you to read back a verification code?",
  },
  {
    kind: "reply",
    text: "Actually yes. Someone called yesterday, said they were from NorthStar security, and I read a code back to them.",
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Thank you for telling me — you did the right thing. Because a security code may have been shared, I want a fraud specialist to review your online-banking access as well as the disputed transactions.",
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Before I connect you, I've already frozen card 1842, identified the two disputed transactions, kept MetroRide marked as yours, and recorded the suspicious call. You won't need to explain any of that again.",
  },
  { kind: "reply", text: "Thank you. I'm really worried they can get into my whole account." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "I understand — the card is already blocked, which removes one avenue of further use. I'm transferring you now to a specialist who can review the rest of your account security. I'll stay on until they're connected.",
  },
  { kind: "handoff", to: "Jordan", role: "Account Protection" },
  {
    kind: "message",
    from: "agent",
    speaker: "Jordan",
    text: "Hi Maya, I'm Jordan with Account Protection. Ava's brought me up to speed — card 1842 is frozen, LUXEMARKET and the $600 ATM withdrawal are disputed, MetroRide is yours, and you received a suspicious call yesterday. You don't need to repeat any of that.",
  },
  { kind: "reply", text: "That's a relief. Can they still log into my bank account?" },
  { kind: "system", text: "Reviewing recent access and security changes…" },
  {
    kind: "message",
    from: "agent",
    speaker: "Jordan",
    text: "I found a login yesterday evening from a device we haven't seen before. I don't see any new payees or successful transfers from that session. I'm revoking all other sessions now, and replacing your card rather than unfreezing it, since its credentials should be treated as compromised.",
  },
  { kind: "reply", text: "Okay — will I be without a card tonight? I need groceries." },
  {
    kind: "message",
    from: "agent",
    speaker: "Jordan",
    text: "We can issue the replacement digitally first, so you can add it to your mobile wallet while the physical card is delivered. I've also opened fraud case FR-982741 covering both disputed transactions — you can track it any time under Help → Claims.",
  },
  { kind: "reply", text: "Added. Am I going to get the $1,884.67 back?" },
  {
    kind: "message",
    from: "agent",
    speaker: "Jordan",
    text: "Both transactions are recorded as unauthorized and the investigation has started. Timing and any credit depend on the transaction type, so I don't want to promise an outcome before that runs — your claim screen will show every status change.",
  },
  {
    kind: "message",
    from: "agent",
    speaker: "Jordan",
    text: "Everything I can see is secure now: the compromised card is blocked, the replacement is active digitally, other sessions are revoked, and your claim is open. Is there anything about today we haven't covered?",
  },
  { kind: "reply", text: "No. I thought I'd spend an hour on the phone. Thank you." },
  {
    kind: "message",
    from: "agent",
    speaker: "Jordan",
    text: "You're welcome, Maya. I'm glad we caught it quickly. The fraud case stays open and we'll proactively keep you updated.",
  },
  {
    kind: "status",
    title: "Customer Protection Status",
    rows: [
      { label: "Compromised card", value: "BLOCKED", positive: true },
      { label: "Replacement card", value: "ACTIVE (digital)", positive: true },
      { label: "Fraud case", value: "FR-982741" },
      { label: "Disputed transactions", value: "2" },
      { label: "Legitimate transaction", value: "PRESERVED", positive: true },
      { label: "Untrusted sessions", value: "REVOKED", positive: true },
      { label: "Customer action needed", value: "NONE", positive: true },
    ],
  },
]

export const collectionsScript: ChatTurn[] = [
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Hi Daniel. You're securely signed in to NorthStar. I'm Ava. I can help with the account ending 4821 — as of today, the amount past due is $286.40. Would you like to make a payment, choose a payment date, or talk through assistance options?",
  },
  { kind: "reply", text: "I need help. I got laid off two weeks ago and the automatic payment bounced." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "I'm sorry you're dealing with that. We can look at the options together — you don't need to share more than is necessary. What would be realistic right now: the full $286.40, part of it, or some time before paying?",
  },
  { kind: "reply", text: "I can do $100 this Friday, Sep 18. I should get unemployment around Oct 2." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Thank you. I'm checking the arrangements available for your account — I won't schedule or move any money unless you review and authorize the terms.",
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "The standard options require the past-due amount sooner than that schedule. A hardship review is available, but this account needs specialist approval before I can offer a modified arrangement. I'll still collect the details so you won't have to start over.",
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "You've said $100 on Sep 18 and additional income around Oct 2 — would another payment in early October work, or would that still risk essential expenses?",
  },
  { kind: "reply", text: "Early October is fine, but rent is due the 1st, so Oct 2 or later is better." },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Understood — no payment before Oct 2 beyond the $100 on Sep 18. Would you prefer future reminders by app notification rather than phone calls?",
  },
  {
    kind: "reply",
    text: "Yes. Please don't call me at work — actually, I don't work there anymore, remove that number too.",
  },
  {
    kind: "message",
    from: "ai",
    speaker: "Ava",
    text: "Absolutely — I've marked your former work number as unavailable for contact and set app notifications as your preference. I'll connect you now to a Payment Assistance specialist who can approve arrangements outside the standard options. You won't need to repeat anything.",
  },
  { kind: "handoff", to: "Sofia", role: "Payment Assistance" },
  {
    kind: "message",
    from: "agent",
    speaker: "Sofia",
    text: "Hi Daniel, I'm Sofia with Payment Assistance. Ava gave me the full summary — the layoff, the $100 on Sep 18, your expected income timing, and the request not to use your old work number. You don't need to go through that again.",
  },
  { kind: "reply", text: "Great — I was worried I'd have to explain the whole thing again." },
  {
    kind: "message",
    from: "agent",
    speaker: "Sofia",
    text: "I can approve an arrangement that fits your timing. Before I explain it, I want to make sure it's actually workable, not just something you agree to and struggle to keep.",
  },
  {
    kind: "payment",
    title: "Payment Arrangement — Review",
    source: "Checking ••••2207",
    rows: [
      { label: "Sep 18", amount: "$100.00" },
      { label: "Oct 2", amount: "$93.20" },
      { label: "Oct 16", amount: "$93.20" },
    ],
    total: "$286.40",
  },
  { kind: "reply", text: "Yes, I can do those dates. How do I make the payments?" },
  {
    kind: "message",
    from: "agent",
    speaker: "Sofia",
    text: "I'll open a secure authorization screen in your app with checking ••••2207 as the source — I won't ask you to type account numbers into this chat. Take your time, and tell me when it's done.",
  },
  { kind: "reply", text: "Done. It says authorized." },
  { kind: "system", text: "Arrangement PT-441872 confirmed." },
  {
    kind: "message",
    from: "agent",
    speaker: "Sofia",
    text: "I see it — arrangement PT-441872 is active, first payment $100 on Sep 18 from checking ••••2207. I've also updated your contact preference so we won't use your former work number.",
  },
  { kind: "reply", text: "Am I still going to get collection messages every day?" },
  {
    kind: "message",
    from: "agent",
    speaker: "Sofia",
    text: "No — now that you have an active arrangement, outreach switches from delinquency messaging to payment-plan servicing. You'll get an app reminder before each payment and a confirmation after each one processes.",
  },
  {
    kind: "message",
    from: "agent",
    speaker: "Sofia",
    text: "If your situation changes and a payment won't work, contact us before the date — the app brings whoever helps you straight back to this arrangement. You're all set for today, Daniel.",
  },
  { kind: "reply", text: "Thank you for actually making this manageable." },
  {
    kind: "status",
    title: "Customer Journey Status",
    rows: [
      { label: "Arrangement", value: "PT-441872" },
      { label: "Next payment", value: "$100.00 — Sep 18" },
      { label: "Future payments", value: "$93.20 — Oct 2 / Oct 16" },
      { label: "Collections outreach", value: "SUPPRESSED", positive: true },
      { label: "Plan reminders", value: "ACTIVE", positive: true },
      { label: "Former work number", value: "SUPPRESSED", positive: true },
      { label: "Customer action needed", value: "NONE until Sep 18", positive: true },
    ],
  },
]

export const scriptsByScenario: Record<string, ChatTurn[]> = {
  fraud: fraudScript,
  collections: collectionsScript,
}

export const caseFiles: Record<string, CaseFile> = {
  fraud: {
    id: "FR-982741",
    scenarioId: "fraud",
    customer: "Maya Chen",
    authNote: "Strongly authenticated in mobile app — Face ID passed",
    intent: "Unauthorized debit-card transactions / possible account takeover",
    facts: [
      "Physical card 1842 remains in customer's possession",
      "No authorized additional user",
      "LUXEMARKET.COM $1,284.67 — NOT AUTHORIZED",
      "QuickCash ATM $600.00 — NOT AUTHORIZED",
      "MetroRide $19.42 — AUTHORIZED",
      "Customer disclosed providing an OTP to an inbound caller yesterday",
    ],
    actionsCompleted: [
      "Card 1842 frozen",
      "Fraud case FR-982741 created",
      "Two disputed transactions attached",
      "Authorized transaction excluded",
    ],
    recommendation: [
      "Review successful and failed logins",
      "Review device enrollment and digital-wallet changes",
      "Revoke untrusted sessions",
      "Replace compromised debit card",
    ],
    reason: "Potential social-engineering / account-takeover event — OTP disclosed to unverified caller.",
  },
  collections: {
    id: "PT-441872",
    scenarioId: "collections",
    customer: "Daniel Brooks",
    authNote: "Authenticated mobile-app session",
    intent: "Delinquency outreach + hardship request",
    facts: [
      "$286.40 currently past due, 17 days delinquent",
      "Reason: recent job loss / income interruption",
      "Customer can pay $100.00 on Sep 18, 2026",
      "Additional income expected around Oct 2, 2026",
      "No second payment before Oct 2 due to essential expenses",
      "Former work phone marked invalid — suppress",
    ],
    actionsCompleted: [
      "Contact preference updated to app notifications",
      "Former work number suppressed",
      "Hardship intake completed",
    ],
    recommendation: [
      "Confirm eligibility in Collections Decision Engine",
      "Explain impact/restrictions of a modified arrangement",
      "If accepted, launch secure authorization workflow",
    ],
    reason: "Requested schedule falls outside standard offer engine — requires exception authority.",
  },
}
